config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'

  devise_for :users

  resources :users, only: [:show, :edit, :update]
  resources :tags,  only: [:index, :show],        param: :tag_name

  resources :prototypes, except: :index do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  scope module: :prototypes do
    resources :newest,  only: :index
    resources :popular, only: :index
  end

end

app/controllers/prototypes/newest_controller.rb
class Prototypes::NewestController < ApplicationController
  def index
    @prototypes = Prototype.eager_load(:user, :prototype_images).all.paginate(page: params[:page]).newest.decorate
    @filter_type = 'newest'
  end
end

app/controllers/prototypes/popular_controller.rb
class Prototypes::PopularController < ApplicationController
  def index
    @prototypes = Prototype.eager_load(:user, :prototype_images).all.paginate(page: params[:page]).popular.decorate
    @filter_type = 'popular'
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :authenticate_user!,          except: [:index, :show]
  before_action :set_prototype,               only:   [:show, :edit, :update, :destroy]
  before_action :set_tag_default_placeholder, only:   [:new, :create, :edit, :update]

  def index
    @prototypes = Prototype.eager_load(:user, :prototype_images).all.paginate(page: params[:page]).decorate
    @filter_type = 'normal'
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
  end

  def new
    @prototype = Prototype.new
    @prototype.prototype_images.build
  end

  def create
    @prototype = current_user.prototypes.new(prototype_params)

    if @prototype.save
      flash[:notice] = 'Prototype was successfully created.'
      redirect_to root_path
    else
      flash[:alert] = 'Prototype was not successfully created.'
      render :new
    end
  end

  def edit

  end

  def update
    if @prototype.update(prototype_params)
      flash[:notice] = 'Prototype was successfully updated.'
      redirect_to root_path
    else
      flash[:alert] = 'Prototype was not successfully updated.'
      render :edit
    end
  end

  def destroy
    if @prototype.user == current_user
      @prototype.destroy
      flash[:notice] = 'Prototype was successfully deleted.'
      redirect_to root_path
    else
      render :index, alert: "You cannot destroy the prototype"
    end
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:id]).decorate
  end

  def set_tag_default_placeholder
    @tag_default_placeholders = ["Web Design", "UI", "Application"]
  end

  def prototype_params
    params.require(:prototype)
        .permit(:name,
                :catchcopy,
                :concept,
                prototype_images_attributes: [:id, :content, :status])
        .merge(tag_list: tag_params)
  end

  def tag_params
    params.require(:prototype).permit(:tag_list)
  end
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/views/prototypes/_filter_type_header.html.haml
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li{ class: "#{ 'active' if filter_type == 'popular' }"}
          = link_to popular_index_path do
            Popular PROTO
        %li{ class: "#{ 'active' if filter_type == 'newest' }"}
          = link_to newest_index_path do
            Newest PHOTO
      = button_to tags_path, method: :get, class: "btn btn-default col-lg-1" do
        View Tags

app/views/prototypes/_form.html.haml
= form_with(model: prototype, local: true) do |form|
  - if prototype.errors.any?
    #error_explanation
      %h2
        = pluralize(prototype.errors.count, "error")
        prohibited this prototype from being saved:
      %ul
        - prototype.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  - if user_signed_in? && current_user.id == prototype.user_id
    .dropdown.drop_menu_location
      %button.btn.btn-default.dropdown-toggle{"aria-expanded": "true", "data-toggle": "dropdown", type: "button"}
        ACTION
      %ul.dropdown-menu
        %li 
          = link_to 'Edit', edit_prototype_path(prototype)
        %li 
          = link_to 'Delete', prototype_path(prototype), method: :delete
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag(prototype.main_image)
      .caption
        %h3 
          = prototype.catchcopy
        .proto-meta
          .proto-date
            = prototype.posted_time

        / tag
        %ul.proto-tag-list.list-inline
          %li
            %a{href: "#", class: "btn btn-default"} iPad  
          %li
            %a{href: "#", class: "btn btn-default"} wireframe

app/views/prototypes/_sub_image.html.haml
%li.list-group-item
	- if sub_image.present?
		= image_tag(sub_image.content, class: 'img-responsive')

app/views/prototypes/_type_header.html.haml
.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{role: "presentation"}
          %a{href: "#"} Popular PROTO
        %li{role: "presentation"}
          = link_to newest_index_path do
            Newest PHOTO
      %button{type: "button", class: "btn btn-default col-lg-1"} View Tags

app/views/prototypes/edit.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = render partial: 'shared/error_message', collection: @prototype.errors.full_messages, as: :error_messages

    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :name, placeholder: 'Name'

      .row
        .col-md-12
          .cover-image-upload#main-prototype-image
            = f.fields_for :prototype_images, @prototype.prototype_images.main.first do |main_image|
              = image_tag @prototype.prototype_images.main.first.content, class: 'main-prototype-image'
              = main_image.file_field :content
              = main_image.hidden_field :status, value: :main

        .col-md-12
          %ul.proto-sub-list.list-group
            - @prototype.sub_images.each_with_index do |sub_image, index|
              %li.list-group-item.col-md-4
                .image-upload{ id: "sub-prototype-image#{index + 1}", data: { sub_image_id: "#{index + 1}" } }
                  = f.fields_for :prototype_images, sub_image do |image|
                    = image_tag sub_image.content, class: 'sub-prototype-image' 
                    = image.file_field :content
                    = image.hidden_field :status, value: :sub

            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +

      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy" 
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: 30, rows: 4 
        .col-md-12
          %h4 Tag List
          .row
            - @tag_default_placeholders.each_with_index do |tag, index|
              .col-md-3
                = text_field_tag "prototype[tag_list][]", @prototype.tags[index], placeholder: "#{tag}"

    .row.text-center.proto-btn
      = f.submit 'Update', class: 'btn btn-lg btn-primary btn-block'

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

= render partial: 'prototypes/filter_type_header', locals: { filter_type: @filter_type }

.container.proto-list
  .row
    = render @prototypes

.text-center
  = will_paginate @prototypes, renderer: BootstrapPagination::Rails

app/views/prototypes/new.html.haml
.container.proto-new
  = form_for @prototype do |f|
    = render partial: 'shared/error_message', collection: @prototype.errors.full_messages, as: :error_messages

    .col-md-8.col-md-offset-2
      %header.row.user-nav.row
        .col-md-12
          .proto-new-title
            = f.text_field :name, placeholder: 'Name'

      .row
        .col-md-12
          .cover-image-upload#main-prototype-image
            = f.fields_for :prototype_images do |image|
              %img.image-preview-prototype
                = image.file_field :content, required: true
                = image.hidden_field :status, value: :main

        .col-md-12
          %ul.proto-sub-list.list-group
            - 2.times do |i|
              %li.list-group-item.col-md-4
                .image-upload{ id: "sub-prototype-image#{i+1}", data: {sub_image_id: "#{i+1}"}}
                  = f.fields_for :prototype_images do |image|
                    %img.image-preview-prototype
                    = image.file_field :content
                    = image.hidden_field :status, value: :sub

            %li.list-group-item.col-md-4
              .image-upload-plus
                %span +

      .row.proto-description
        .col-md-12
          = f.text_field :catchcopy, placeholder: "Catch Copy" 
        .col-md-12
          = f.text_area :concept, placeholder: "Concept", cols: 30, rows: 4 
        .col-md-12
          %h4 Tag List
          .row
            - @tag_default_placeholders.each do |tag|
              .col-md-3
                = text_field_tag "prototype[tag_list][]", "", placeholder: "#{tag}"
      .row.text-center.proto-btn
        = f.submit 'Publish', class: 'btn btn-lg btn-primary btn-block'
      

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user_avatar, class: 'media-object', style: 'width: 64px; height: 64px')
        .media-body
          %h4#top-aligned-media.media-heading
          = @prototype.name
          .proto-user
            = link_to user_path(@prototype.user) do
              by #{@prototype.user_name}
            %span.degree
            = @prototype.user_profile

    .col-md-6.text-right
      = render partial: 'likes/like', locals: { prototype: @prototype }

  .row
    .col-md-9
      = image_tag(@prototype.main_image, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        = render partial: 'prototypes/sub_image', collection: @prototype.sub_images, as: :sub_image
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.catchcopy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        - @prototype.tags.each do |tag|
          = link_to tag, tag_path(tag), class: "button btn btn-default"
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span.num
        = "(#{@prototype.comments_num})"
    .col-md-8
      .comments_list
        = render @comments

      - if user_signed_in?
        = form_for [@prototype, @comment], html: { class: 'form-online' }, remote: true do |f|
          %h4 Write a comment
          .row
            .form-group.col-md-10
              = f.text_area :text, class: 'form-control', placeholder: 'Your comments', rows: 3
            .form-group.col-md-2
              = f.submit 'Comment', class: 'btn btn-primary'