config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'

  devise_for :users

  resources :users, only: [:show, :edit, :update]
  resources :tags,  only: [:index, :show],        param: :tag_name

  resources :prototypes, except: :index do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  scope module: :prototypes do
    resources :newest,  only: :index
    resources :popular, only: :index
  end

end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id           :integer          not null, primary key
#  user_id      :integer          not null
#  prototype_id :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Like < ApplicationRecord

  # Association
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count

  # Validation
  validates :user_id, uniqueness: { scope: :prototype_id }
  validates :user_id, :prototype_id, presence: true, numericality: true

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :set_prototype,      only: [:create, :destroy]

  def create
    @prototype.likes.create(user_id: current_user.id)
  end

  def destroy
    @prototype.likes.find_by(user_id: current_user.id).destroy
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:prototype_id]).decorate
  end
end

app/views/likes/_form.html.haml
= form_with(model: like, local: true) do |form|
  - if like.errors.any?
    #error_explanation
      %h2
        = pluralize(like.errors.count, "error")
        prohibited this like from being saved:
      %ul
        - like.errors.full_messages.each do |message|
          %li= message
  .actions
    = form.submit

app/views/likes/_like.html.haml
- if prototype.is_liked_current_user?
  = button_to prototype_like_path(prototype, current_user), method: :delete, class: "button btn btn-default", remote: true do
    = render partial:'likes/liked', locals: { prototype: prototype }
- else
  - if user_signed_in?
    = button_to prototype_likes_path(prototype), class: "button btn btn-default", remote: true do
      = render partial:'likes/non_liked', locals: { prototype: prototype }
  - else
    = button_to new_user_session_path, method: :get, class: "button btn btn-default" do
      = render partial:'likes/non_liked', locals: { prototype: prototype }

app/views/likes/_liked.html.haml
= image_tag("icon_red_heart.svg")
%span
= "Like #{prototype.likes_num}"

app/views/likes/_non_liked.html.haml
= image_tag("icon_heart.svg")
%span
= "Like #{prototype.likes_num}"

app/views/likes/create.js.erb
$(".col-md-6.text-right")
  .html("<%= j(render partial: 'likes/like', locals: { prototype: @prototype }) %>");

app/views/likes/destroy.js.erb
$(".col-md-6.text-right")
  .html("<%= j( render partial: 'likes/like', locals: { prototype: @prototype } ) %>");