config/routes.rb
Rails.application.routes.draw do
  root 'prototypes#index'

  devise_for :users

  resources :users, only: [:show, :edit, :update]
  resources :tags,  only: [:index, :show],        param: :tag_name

  resources :prototypes, except: :index do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: :create
  end

  scope module: :prototypes do
    resources :newest,  only: :index
    resources :popular, only: :index
  end

end

app/views/shared/_error_message.html.haml
- if error_messages.present?
  %ul 
    %li 
      = error_messages

app/views/shared/_flash_messages.html.haml
- flash.each do |key, value|
	- key = "success" if key == "notice"
	- key = "danger" if key == "alert"
	= content_tag :div, value, class: "alert alert-#{key}"

app/views/shared/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2017.
    

app/views/shared/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse 
      - if user_signed_in?
        / sign_in
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button"}
              = current_user.name
              %span.caret
            %ul.dropdown-menu{role: "menu"}
              %li
                = link_to user_path(current_user) do
                  My Page
              %li
                = link_to edit_user_path(current_user) do
                  Profile Edit
              %li
                = link_to destroy_user_session_path, method: :delete do
                  Logout
          %li
            .btn.btn-primary.navbar-btn
              = link_to new_prototype_path do
                New Proto

      - else
        //not sign_in yet
        %ul.nav.navbar-nav.navbar-right
          %li
            .btn.btn-primary.navbar-btn
              %a{href: "/users/sign_in"}
                Get Started